### ISSUE TITLE
Library not registered Issues with 0.8.4 version

### ISSUE THREAD

**Issue by kopmark42** [OlapPivotTableExtensions/OlapPivotTableExtensions#5] opened 2017-12-11 17:21 UTC
PC has recently been rebuilt to a Win 10 1703 image. I am running Excel 2010 version 14.0.7190.5000 (32 bit). OLAP installs without issue, but when I try to use the functionality (typically filtering), am getting the following error message.

Any help would be greatly appreciated

Thanks!

Mark
 
![olap error](https://user-images.githubusercontent.com/34454098/33844198-77df919e-de97-11e7-837b-1995a19d5c31.PNG)

**Comment by furmangg** [comment] 2017-12-11 20:36
Can you screenshot the About tab please?

**Comment by kopmark42** [comment] 2017-12-12 10:56
Hi,

Here you go.

Thanks!

Mark

[cid:image001.png@01D37337.D9360CF0]

[cid:image002.png@01D37337.D9360CF0]

**Comment by furmangg** [comment] 2017-12-12 13:16
Unfortunately the image didn't come through online. Can you try again from a web browser?

**Comment by kopmark42** [comment] 2017-12-12 13:21
![olap about](https://user-images.githubusercontent.com/34454098/33886669-42266494-df3f-11e7-86c8-d271e6f2c222.png)
![excel about](https://user-images.githubusercontent.com/34454098/33886678-49c09422-df3f-11e7-815a-9687713804f1.png)

**Comment by kopmark42** [comment] 2017-12-12 13:25
Thanks again for your help!

**Comment by furmangg** [comment] 2017-12-15 01:33
I notice the languages don't match. Does this article describe your situation? Can you figure out a way to get your languages to match?

https://olappivottableextensions.github.io/Unsupported-Language-Configuration.html

**Comment by kopmark42** [comment] 2017-12-15 11:16
Hi, I've matched all the languages, and done a fresh install of the plugin. Still getting the same error...
![olap error2](https://user-images.githubusercontent.com/34454098/34039914-5eb44d1e-e189-11e7-8cd5-fa37b220a51b.PNG)

**Comment by kopmark42** [comment] 2018-01-04 14:52
Hi, was just wondering if you had any update on this issue?
Many thanks!!
Mark

**Comment by furmangg** [comment] 2018-01-04 19:31
I'm unable to reproduce this. Is upgrading to a newer Excel out of the question?

I suppose it's worth a shot to uninstall OLAP PivotTable Extensions and reinstall an old build which was the latest prior to Excel 2013 being supported:
https://olappivottableextend.codeplex.com/releases/view/81169

That's a bit of a long shot.

**Comment by furmangg** [comment] 2018-02-14 21:25
Another similar issue was resolved by uninstalling Skype for Business 2016:
https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/issues/6#issuecomment-365749808

**Comment by kopmark42** [comment] 2018-02-26 14:39
Hi, i was able to upgrade to MS 365. We are advising other users in the organization to do the same. I will try the uninstall of Skype to see if that was the issue, however it is not an option, as it is also used extensively. Thanks for your help!

**Closed** 2021-11-24 20:59 UTC
Labels: can't reproduce
